### ISSUE TITLE
Initial org repo issue suggests user error and has broken link

### ISSUE THREAD

**Issue by jasonkuhrt** [maticzav/label-sync#186]
Example https://github.com/prisma-labs/prisma-labs-labelsync/issues/1

- As a user, having done nothing, I did not expect that issue.
- The `starting template` link has a typo and navigates to a 404

**Comment by maticzav** [comment]
@jasonkuhrt would you prefer having a setup call to having an autogenerated template? I can't decide between the two for onboarding new people, but the latter sounds very interesting.

**Comment by jasonkuhrt** [comment]
Can't it just be a PR? Maybe something to learn about how Renovate repo onbaording words. They even do stuff like have checkboxes which when clicked will make the PR "refresh itself".

**Comment by maticzav** [comment]
@jasonkuhrt the problem is that we need a central repository. That’s why we need a bootstrap method. Maybe the initial PR wouldn’t come with TS and would only pack yaml file instead.

**Comment by jasonkuhrt** [comment]
Not sure I understand. Maybe we can go deeper in the call next week?
