### ISSUE TITLE
Siblings?

### ISSUE THREAD

**Issue by janpio** [maticzav/label-sync#66]
Over at https://github.com/prisma/prisma-label-sync we use `siblings` for bug qualification: `bug/0-need-info`, `bug/1-has-repo` and `bug/2-confirmed` are configured to have `kind/bug` as siblings:

https://github.com/prisma/prisma-label-sync/blob/51f917e3d7870a7ce0c94da5ba152eec32d2d98a/src/labels/common/prisma2.ts#L14-L32

Now we introduced `kind/regression` which is a `kind/bug` with some additional meaning. 

How can I configure that so that the tool is happy for the `bug/*` labels with _either_ `kind/bug` _or_ `kind/regression`? Currently it re-adds `kind/bug` to all the `kind/regression` only issues.

**Comment by maticzav** [comment]
@janpio `label-sync` currently doesn't support that. For the reference, `kind/regression` doesn't have any siblings; `label-sync` adds them due to `bug/*`s.

**Comment by janpio** [comment]
So the siblings functionality "only" supports one specific "parent" that will automatically be added for the labels it is defined, correct? 

(Makes sense of course, how should it decide which label to choose otherwise and add automatically)
