### ISSUE TITLE
Better error handling, more information about error source

### ISSUE THREAD

**Issue by janpio** [maticzav/label-sync#71]
# Feature request

## Is your feature request related to a problem? Please describe

Currently the error message you get when something goes wrong when talking to Github doesn't have any context what exactly the script was trying to do - it just tells you an error happened.

2 examples:

- https://github.com/prisma/prisma-label-sync/issues/51 - Here we got "HttpError: Not Found" because of some unknown reason, it fixed itself but we still don't know what exactly was wrong so it was only solved by chance.
- https://circleci.com/gh/prisma/prisma-label-sync/216 - Here we get "HttpError: Server Error" with no context. My current guess is that the user/token we are using can not access this repo or at least not create labels there (Will report back after we fixed this - Update: Indeed giving the bot user the necessary rights fixed this error - so "Server Error" might sometimes mean "your token/user does not have access")

## Describe the solution you propose

It would be nice if the error message would not just output the error message, but also what it was doing when things went wrong: What URL was it requesting? What action was it trying to execute? What changes did it want to make to the repo? What repo was it working on when the error happened?

## Describe alternatives you've considered

Try anything I can think of that could possibly have gone wrong.

**Comment by maticzav** [comment]
Thank you for opening the issue. I'll close it since the next version will communicate through Github App.
