### ISSUE TITLE
Also support milestones

### ISSUE THREAD

**Issue by janpio** [maticzav/label-sync#72]
# Feature request

Current goal of this tool:

> Label Sync helps you sync Github labels across multiple repositories.

I suggest to add "... and milestones" to that.

## Is your feature request related to a problem?

Prisma uses `label-sync`, and our software lives in many repositories. We recently switched from using labels (`release/preview-5`) to using milestones to plan the work we want to achieve in a sprint.

So previously it was enough to add the preview to the label sync configuration, and it would be created across all repositories. Then we could use `label:release/preview-5` in the search to see all the relevant issues.

As GitHub doesn't support cross repository milestones (as it doesn't support cross repository labels), we have to do the same now for milestones and use `milestone:"Preview 5"` for search. 

But the creation of these milestones is a similar amount of work as creation of labels: They need a name, a description and a due date, if any of that changes we have to go through our growing number of repositories to update it.

(see also https://github.com/prisma/prisma-label-sync/issues/42 where this is mainly copy/pasted from)

## Describe the solution you propose

It would be neat if `label-sync` could handle milestones in a similar way that it handles labels: Define them in code, run the script, everything gets set up or updated for you.

## Describe alternatives you've considered

a) Do it manually

b) Use existing tools or services

https://github.com/vanilla/github-sync
https://github.com/matomo-org/github-sync
https://help.codetree.com/en/articles/2605231-working-with-multiple-repositories#codetree-automatically-adds-labels-and-milestones-to-all-repos-in-a-project

c) Create a new tool

We could also create a new thing that does this.

## Additional context

As we are currently using Codetree for other reasons, it might actually be a good solution for us to use it to create and sync the milestones as well. I wanted to create this issue here anyway, as it could really be useful for other users as well - but no real need for us there (until I find something that is broken in Codetree).

**Comment by maticzav** [comment]
Will support this!

**Comment by janpio** [comment]
(Important to know: I decided to close this as I found a workaround in Codetree.com - which matches our requirements much better than having to change code to create milestones, which just would have been better than to do it manually in all repos. Having the nice UI of Codetree make this obsolete for us, so this would definitely not be a feature we would use.)

**Comment by maticzav** [comment]
Makes sense, thanks!
