### ISSUE TITLE
Label Sync Check Hangs on Dry Run if YML has entry with Alias and Name set to the same value.

### ISSUE THREAD

**Issue by sysnet-ai** [maticzav/label-sync#783]
# Bug report

- [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug
Having a label with an alias equal to itself seems to hang the dry-run process.

## To Reproduce
I have a simple yml based on the setup one from yarn. While editing for my use, I ended up creating this entry:
```yml
  "bug":
    color: &bug
    description: A bug
    alias: ["bug"]
```
I assume an alias being the same as the name is causing some unexpected behavior.

## Expected behavior
Either an error if this isn't allowed, or the job finishing within normal time frames. A cancel button to stop the action once it starts misbehaving would also be nice.

## Actual behaviour

![Screen Shot 2021-05-24 at 9 34 46 AM](https://user-images.githubusercontent.com/16857363/119378687-619ef380-bc73-11eb-82d7-de5794235ec1.png)
20+ Minutes running, closing the PR or deleting the branch don't seem to cancel it.

**Comment by sysnet-ai** [comment]
Closing this out as it ended up being something different.
Thanks @maticzav for the offline help.

**Comment by tayloramurphy** [comment]
@sysnet-ai can you share more about the problem? I'm seeing the same long running dryrun job, but not sure if it's related to your issue here.
