### ISSUE TITLE
Your format is unknown - bot does not recognize it as yaml file?

### ISSUE THREAD

**Issue by ngehani** [maticzav/label-sync#785]
# Explain your question

- [ x] I have checked existing issue and found none that could answer my question.

Describe your question in as much detail as possible.
If possible include context, source of the problem, and the end goal you are trying to achieve.

> I encourage you to try and make an issue with one of the other templates before submitting the general form.
I have a .yml file and when I make a commit the bot runs and says the format is unknown to it. I am using vscode and it looks like a yaml file so I don't know where to check to ensure its the right file and format for the bot to process 

![image](https://user-images.githubusercontent.com/5252285/120689895-97fa2100-c472-11eb-8eb6-35ee38f0df8e.png)

**Comment by ngehani** [comment]
I tried it with and without a new line

**Comment by ngehani** [comment]
I tried multiple ways to use YAML linters like the one built in vscode, the redhat version, and yamllint.com and none of them give an error in the YAML file and all recognize it as a valid yaml file. 

Ran out of ideas on where to look

**Comment by maticzav** [comment]
Hi @ngehani,

There was an issue in the template. You should change the "&" signs when assigning colors to labels to "*".

I can see that the format of the error doesn't help at all. I am working on it! Let me know if that solves it for you.
