### ISSUE TITLE
Repository level configuration to ignore unknown labels

### ISSUE THREAD

**Issue by janpio** [maticzav/label-sync#88]
Currently `label-sync` by default removes all the unknown labels from a repository. That is fine most of the times, but sometimes you want to have a more free form label set that allows you to just create things additionally that are not touched by `label-sync`.

It would be nice if we could configure this on a repository level.

**Comment by maticzav** [comment]
There's an existing `strict` parameter which allows you to toggle that. You can read more about it [here](https://github.com/maticzav/label-sync#types).

**Comment by janpio** [comment]
So setting `strict: false` on a repository will allow me to keep additional labels?
The link you provided doesn't have any actual documentation on `strict`, just where to use it, unfortunately.
Will this only apply to additional labels, or also to other changes like color and description?

**Comment by maticzav** [comment]
Indeed. Unfortunately it’s only labels - it doesn’t delete any label.

**Comment by janpio** [comment]
Interesting, you should definitely add that information to the docs.

Here is what I get:

```
Removed Labels: (5)
- area/binaries
- area/cli-init
- area/cloud-platforms
- area/photonjs
- area/schema

We haven't removed any label yet.
If you want us to remove them, set strict to true.
```

![image](https://user-images.githubusercontent.com/183673/66722209-1839c180-ee0b-11e9-80df-12f3a4b4ecd7.png)

That means that it will _not_ remove these when I actually run this instead of dry-run? The wording of "Removed Labels" makes me not sure what will happen.

(An interesting follow up thing might be a way to manually once run with `strict: true` to clean up a repository and its labels.)

**Comment by maticzav** [comment]
The wording is a bit strange, but you are right. That code won't delete anything. 

Re. `cleanup`: maybe we could have a message to clean everything up once publishing a new configuration.

**Comment by janpio** [comment]
Will try that out if it works tomorrow: https://github.com/prisma/prisma-label-sync/pull/81 ;)
