### ISSUE TITLE
Support label renaming

### ISSUE THREAD

**Issue by janpio** [maticzav/label-sync#91]
Current workaround: Rename the labels manually, then execute `label-sync`. Then the existing labels do not get deleted and recreated and as such can keep their issues.

**Comment by maticzav** [comment]
Current workaround: 

1. Add a sibling to a label you are renaming, and run `label-sync`.
2. Replace the old label with the renamed one, and run `label-sync`.

**Comment by maticzav** [comment]
Should be supported with `alias` property.
