### ISSUE TITLE
Output current configuration

### ISSUE THREAD

**Issue by janpio** [maticzav/label-sync#93]
It would be neat if there was a way to output the current configuration, that would make it obsolete to look at the code.

Variants:
- Another Circle job that just outputs all repos with the labels that should exist there. You can go to the last commit, open that job and see the overview
- A website is generated and committed to `gh-pages` branch and made available via GitHub pages. You just open the URL to get the currently active configuration.

**Comment by maticzav** [comment]
I love the second idea.
